services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  application:
    image: rabbitmq-demo:0.0.1-SNAPSHOT
    environment:
      spring.rabbitmq.host: rabbitmq
